file = open("Example.txt")
print(file)
file.close()
file = open("Example.txt", "w")
file.write("Over written text")
file.close()
file = open("Example.txt", "r")
print(file.read())
file.close()
file = open("Example.txt", "a")
file.write(" New appended text")
file.close()
file = open("Example.txt", "r")
file.close()
file = open("Example.txt", "r")
print(file.read())